gpio:
  servo_pin: 12
  motor_pin: 13
  init_pwm: 12600
  target_pwm: 13100

frame:
  width: 300
  height: 200

initialThreshold: 200

linedetect:
  onnxmodelpath: "/home/pi/Code/5GSmartCar/models/arrow-yolo11n-cls-v3.onnx"

video:
  isvideo: true
  videopath: "/home/pi/Code/5GSmartCar/medias/crosswalk.mp4"

audio:
  playaudio: false
  audiopath: "/home/pi/Code/5GSmartCar/medias/sunshangxiang.wav"

movecontrol: false

recordvideo: false

loglevel: "DEBUG"