gpio:
  servo_pin: 12
  motor_pin: 13
  init_pwm: 12600
  target_pwm: 13100

frame:
  width: 300
  height: 200

initialThreshold: 80

linedetect:
  onnxmodelpath: "/home/pi/Code/5GSmartCar/models/arrow-yolo11n-cls-v3.onnx"

conedetector:
  upperblue:
    H: 120
    S: 255
    V: 255
  lowerblue:
    H: 80
    S: 210
    V: 60

video:
  isvideo: false
  videopath: "/home/pi/Code/5GSmartCar/medias/playground2.avi"

audio:
  playaudio: false
  audiopath: "/home/pi/Code/5GSmartCar/medias/sunshangxiang.wav"

movecontrol: true

recordvideo: false

loglevel: "DEBUG"