gpio:
  servo_pin: 12
  pwm_pin: 13
  init_pwm: 12600
  target_pwm: 13000

frame:
  width: 300
  height: 200

linedetect:
  onnxmodelpath: "/home/pi/Code/5GSmartCar/models/arrow-yolo11n-cls-v3.onnx"

video:
  isvideo: false
  videopath: "/home/pi/Code/5GSmartCar/medias/arrow.avi"

audio:
  isaudio: false
  audiopath: "/home/pi/Code/5GSmartCar/medias/dz-banmaxian.wav"

movecontrol: false

loglevel: "DEBUG"