gpio:
  servo_pin: 12
  pwm_pin: 13

frame:
  width: 300
  height: 200

linedetect:
  onnxmodelpath: "/home/pi/Code/5G_ws/models/arrow-yolo11n-cls-v2.onnx"

video:
  isvideo: true
  videopath: "/home/pi/Code/5G_ws/medias/arrow.avi"